package com.minuk3y.payroll_finals;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

public class owner_menu extends javax.swing.JFrame {
    
    Connection con;
    PreparedStatement insert;
    String default_ownername;
    static Object editselectedValue;
    


    public owner_menu() {
        try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
                insert = con.prepareStatement("select * from owner");
                ResultSet rs = insert.executeQuery();
                    while (rs.next()){
                        default_ownername = rs.getString(1);
                        
                    }
            } catch (Exception ex) {
                System.out.println(ex);
            
        
        }
        initComponents();
            }
    
    //updates combobox when owner_menu is opened
    public void combobox_update() {
    try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
                insert = con.prepareStatement("select employee_name from employees");
                ResultSet rs = insert.executeQuery();
                while(rs.next()){
                    String name = rs.getString("employee_name");
                    jc_select_employee.addItem(name);
                }
               
            } catch (Exception ex) {
                System.out.println(ex);
            } 
}
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login_title = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jb_changeusern = new javax.swing.JButton();
        jb_logout = new javax.swing.JButton();
        jc_select_employee = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jb_changepass1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jb_checkpayrolls = new javax.swing.JButton();
        add_employee = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Menu");

        Login_title.setFont(new java.awt.Font("A-OTF Shin Go Pro EL", 0, 18)); // NOI18N
        Login_title.setText("Welcome " + default_ownername +" !");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.BOTTOM, new java.awt.Font("A-OTF Shin Go Pro R", 0, 12))); // NOI18N

        jb_changeusern.setText("Change Username");
        jb_changeusern.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_changeusern.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_changeusernActionPerformed(evt);
            }
        });

        jb_logout.setText("Log out");
        jb_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_logoutActionPerformed(evt);
            }
        });

        jc_select_employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jc_select_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jc_select_employeeActionPerformed(evt);
            }
        });

        jLabel1.setText("Select Employee:");

        jb_changepass1.setText("Change Password");
        jb_changepass1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_changepass1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_changepass1ActionPerformed(evt);
            }
        });

        jButton1.setText("Edit");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jb_checkpayrolls.setText("Check Current Payrolls");
        jb_checkpayrolls.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jb_checkpayrolls.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_checkpayrollsActionPerformed(evt);
            }
        });

        add_employee.setText("Add Employee");
        add_employee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add_employee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_employeeActionPerformed(evt);
            }
        });

        jButton2.setText("Delete");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(204, 0, 0));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jb_changepass1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jb_logout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jb_changeusern, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE))
                        .addGap(17, 17, 17))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                    .addGap(74, 74, 74)
                                    .addComponent(add_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jc_select_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jButton2))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jb_checkpayrolls, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jc_select_employee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_checkpayrolls, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(add_employee, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jb_changeusern, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_changepass1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jb_logout))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(Login_title))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(206, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(Login_title)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jb_changeusernActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_changeusernActionPerformed
        setVisible(false);
        new change_username().setVisible(true);
    }//GEN-LAST:event_jb_changeusernActionPerformed

    private void jb_logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_logoutActionPerformed
        setVisible(false);
        new LoginPage().setVisible(true);
    }//GEN-LAST:event_jb_logoutActionPerformed

    private void jb_changepass1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_changepass1ActionPerformed
        setVisible(false);
        new change_password().setVisible(true);
    }//GEN-LAST:event_jb_changepass1ActionPerformed
    
    //opens employee_menu() when edit button is clicked
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        editselectedValue = jc_select_employee.getSelectedItem();
        if (editselectedValue == null || editselectedValue.toString().isEmpty()){
        jLabel2.setText("No Employee Selected.");
    }
        else{
        setVisible(false);
        new employee_menu().setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    //opens current_payrolls() when Check Current Payrolls button is clicked
    private void jb_checkpayrollsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_checkpayrollsActionPerformed
        setVisible(false);
        current_payrolls cp = new current_payrolls();
        cp.update_table();
        cp.setVisible(true);
    }//GEN-LAST:event_jb_checkpayrollsActionPerformed

    private void add_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_employeeActionPerformed
        setVisible(false);
        new add_employee().setVisible(true);
    }//GEN-LAST:event_add_employeeActionPerformed

    //deletes values from the database when delete button is clicked
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        editselectedValue = jc_select_employee.getSelectedItem();
        if (editselectedValue == null || editselectedValue.toString().isEmpty()){
        jLabel2.setText("No Employee Selected.");
        }
        else{
            try {
            Object selectedValue = jc_select_employee.getSelectedItem();
            int dialogresult  = JOptionPane.showConfirmDialog(null,"Do you want to Delete this Employee?","Warning",JOptionPane.YES_NO_OPTION);
            if(dialogresult == JOptionPane.YES_OPTION){
            Class.forName("com.mysql.cj.jdbc.Driver");
                con=DriverManager.getConnection("jdbc:mysql://localhost:3306/payroll","root","");
                insert = con.prepareStatement("delete from employees where employee_name=?");
                
                insert.setString(1, selectedValue.toString());
                insert.executeUpdate();
                
                JOptionPane.showMessageDialog(this,"Employee Successfully Deleted!");
                
                setVisible(false);
                owner_menu om = new owner_menu();
                om.combobox_update();
                om.setVisible(true);;
               
            }
            
               
            } catch (Exception ex) {
                System.out.println(ex);
            } 
            
    }
              
            
               
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jc_select_employeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jc_select_employeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jc_select_employeeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel Login_title;
    private javax.swing.JButton add_employee;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton jb_changepass1;
    private javax.swing.JButton jb_changeusern;
    private javax.swing.JButton jb_checkpayrolls;
    private javax.swing.JButton jb_logout;
    private javax.swing.JComboBox<String> jc_select_employee;
    // End of variables declaration//GEN-END:variables
}
